[package]
name = "iron-mockside"
version = "0.2.0"
authors = ["Ovidiu Ionescu <ovidiu@ionescu.net>"]
edition = "2018"

[dependencies]
itertools="*"
regex="*"
lazy_static="*"
kmp="*"
clap="*"
log="*"
stderrlog = "*"